apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: ibm-spectrum-scale
  app.kubernetes.io/name: operator

namespace: ibm-spectrum-scale-operator
namePrefix: ibm-spectrum-scale-

resources:
- ../../base

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

images:
- digest: sha256:dd543baefcb9ec4db696b63c3a1c2b318146f9837c8cf4f4ccabaee7b95a10ec
  name: controller
  newName: icr.io/cpopen/ibm-spectrum-scale-operator

components:
- ../../components/rbac/deploy
- ../../components/rbac/regionaldr
- ../../components/rbac/gui
- ../../components/webhook/deploy
- ../../components/manager/deploy
