apiVersion: builtin
kind: LabelTransformer
metadata:
  name: versionLabeler
labels:
  # DO NOT USE THE MINUS/DASH CHARACTER (-) AS PART OF THE VERSION NUMBER.
  # i.e v5.1.9.1-1 is NOT VALID, USE v5.1.9.1.1 INSTEAD.
  app.kubernetes.io/version: v5.1.9.7
fieldSpecs:
  - kind: Deployment
    path: metadata/labels
    create: true
  - kind: Deployment
    path: spec/template/metadata/labels
    create: true
